import { useState } from "react";
import API from "../../services/api";
import StockTable from "../ui/StockTable";
import Loader from "../ui/Loader";
import ErrorBanner from "../ui/ErrorBanner";

export default function AIScreener() {
  const [query, setQuery] = useState("");
  const [stocks, setStocks] = useState([]);
  const [filters, setFilters] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const examples = [
    "Find stocks with PE below 30",
    "Find IT stocks with PE below 25",
    "Find the top 5 stocks with PE below 30",
  ];

  const runAI = async () => {
    // Do not send an empty request to the backend
    if (!query.trim()) {
      setError("Please describe the stocks you are looking for.");
      return;
    }

    try {
      setLoading(true);
      setError("");
      setStocks([]);
      setFilters(null);

      // Send the natural-language request to our AI screener
      const res = await API.post("/stocks/ai-screener", {
        query: query.trim(),
      });

      setStocks(res.data.data || []);
      setFilters(res.data.filtersApplied || null);
    } catch (err) {
      console.error("AI Screener error:", err);

      setError(
        err.response?.data?.message ||
        "Unable to run the AI screener. Please try again."
      );
    } finally {
      setLoading(false);
    }
  };

  const handleExample = (example) => {
    setQuery(example);
    setError("");
  };

  const handleKeyDown = (event) => {
    // Ctrl + Enter runs the screener quickly
    if (event.ctrlKey && event.key === "Enter") {
      runAI();
    }
  };

  return (
    <section className="ai-screener-card">

      {/* AI screener introduction */}
      <div className="ai-screener-header">
        <div>
          <span className="eyebrow">AI-POWERED SEARCH</span>

          <h2>Find Stocks in Plain English</h2>

          <p>
            Describe the stocks you are looking for and StockVision
            will translate your request into financial screening rules.
          </p>
        </div>

        <div className="ai-status">
          <span className="status-dot"></span>
          AI Engine Ready
        </div>
      </div>

      {/* Natural language input */}
      <div className="ai-input-area">

        <textarea
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Example: Find IT stocks with PE below 30 and debt to FCF below 1"
          disabled={loading}
        />

        <div className="ai-input-footer">
          <span>
            Press <strong>Ctrl + Enter</strong> to run
          </span>

          <button
            className="ai-run-button"
            onClick={runAI}
            disabled={loading}
          >
            {loading ? "Analyzing..." : "Run AI Screener →"}
          </button>
        </div>

      </div>

      {/* Example queries */}
      <div className="example-section">

        <span>Try an example</span>

        <div className="example-buttons">
          {examples.map((example) => (
            <button
              key={example}
              className="example-button"
              onClick={() => handleExample(example)}
              disabled={loading}
            >
              {example}
            </button>
          ))}
        </div>

      </div>

      {/* Loading state */}
      {loading && (
        <div className="ai-loading">
          <Loader />
          <p>
            AI is translating your request into screening rules...
          </p>
        </div>
      )}

      {/* Error message */}
      {!loading && error && (
        <ErrorBanner message={error} />
      )}

      {/* Screening results */}
      {!loading && stocks.length > 0 && (
        <div className="ai-results">

          <div className="results-header">
            <div>
              <span className="eyebrow">SCREENING RESULTS</span>

              <h3>
                {stocks.length} stock{stocks.length !== 1 ? "s" : ""} found
              </h3>
            </div>
          </div>

          {/* Show the rules generated by the AI */}
          {filters && (
            <div className="filters-applied">

              <div className="filters-title">
                <span>AI-generated filters</span>
              </div>

              <div className="filter-list">

                {filters.filters?.map((filter, index) => (
                  <span className="filter-chip" key={index}>
                    {filter.field} {filter.operator} {filter.value}
                  </span>
                ))}

                {filters.sector && (
                  <span className="filter-chip">
                    Sector: {filters.sector}
                  </span>
                )}

                {filters.limit && (
                  <span className="filter-chip">
                    Top {filters.limit}
                  </span>
                )}

                {filters.sort && (
                  <span className="filter-chip">
                    Sort: {filters.sort.field}{" "}
                    {filters.sort.direction}
                  </span>
                )}

              </div>
            </div>
          )}

          <StockTable stocks={stocks} />

        </div>
      )}

      {/* Empty state before the first search */}
      {!loading && !error && stocks.length === 0 && (
        <div className="ai-empty-state">
          <div className="empty-icon">✦</div>

          <h3>Start your stock search</h3>

          <p>
            Tell StockVision what kind of companies you want to find.
          </p>
        </div>
      )}

    </section>
  );
}